name: Build and Deploy
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite 🛠️
        run: |
          pip install jupyterlite jupyterlab jupyterlite-pyodide-kernel numpy scipy sympy matplotlib

      - name: Build JupyterLite 🏗️
        run: |
          # Builds notebooks from your /docs/notebooks folder into a /dist directory
          jupyter lite build --contents docs/notebooks --output-dir dist/lite

      - name: Set up Ruby 💎
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Build Jekyll 🧪
        run: |
          # Build your Jekyll site from the /docs folder into the same /dist directory
          # Uses [GitHub Actions for Jekyll](https://jekyllrb.com/docs/continuous-integration/github-actions/)
          bundle install
          bundle exec jekyll build --source docs --destination dist

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Deploys the combined output
          branch: gh-pages